version: 2.1
orbs:
  node: circleci/node@4.1

jobs:
  pet-shop-e2e-tests:
    docker:
      - image: cimg/node:15.1-browsers
    working_directory: ~/repo
    environment:
      adminEmail: admin@buckhill.co.uk
      adminPassword: admin
    steps:
      - checkout
      - run:
          name: "Setup custom environment variables"
          command: echo 'export MY_ENV_VAR="admin@buckhill.co.uk"' >> "$BASH_ENV"
          command: echo 'export MY_ENV_VAR="admin"' >> "$BASH_ENV"
      - run:
          name: Install npm dependencies
          command: |
            npm install
      - run:
          name: Run tests
          command: |
            npm test
      - store_artifacts:
          path: allure-report/

workflows:
  version: 2
  commit:
    jobs:
      - pet-shop-e2e-tests
  periodical:
    triggers:
      - schedule:
          cron: "0 10 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - pet-shop-e2e-tests
      