version: 2.1
orbs:
  node: circleci/node@4.1

jobs:
  pet-shop-e2e-tests:
    docker:
      - image: cimg/node:15.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo 'export adminEmail="${echo $adminEmail | base64 -d}"' >> $BASH_ENV
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo 'export adminPassword="${echo $adminPassword | base64 -d}"' >> $BASH_ENV
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm dependencies
          command: |
            npm install
      - run:
          name: Install Allure plugin
          command: sudo npm install -g allure-commandline --save-dev
      - save_cache:
          paths:
            - node_modules
            - ~/.cache
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: |
            npx cypress run --env allure=true
      - run:
          name: Generate allure report
          command: allure generate
          when: always
      - store_artifacts:
          path: allure-report/
      - store_artifacts:
          path: output/videos

workflows:
  version: 2
  commit:
    jobs:
      - pet-shop-e2e-tests
  periodical:
    triggers:
      - schedule:
          cron: "0 10 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - pet-shop-e2e-tests
      