version: 2.1
jobs:
  pet-shop-e2e-tests:
    docker:
      - image: cypress/base:10
    working_directory: ~/repo
    environment:
      adminEmail: adminEmail
      adminPassword: adminPassword
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install
      - run:
          name: Run tests
          command: |
            npm test
      - store_artifacts:
          path: allure-report/

workflows:
  version: 2
  commit:
    jobs:
      - pet-shop-e2e-tests
  periodical:
    triggers:
      - schedule:
          cron: "0 10 * * 1-5"
          filters:
            branches:
              only:
                - mai
    jobs:
      - pet-shop-e2e-tests      